version: '3.3'
services:
  app:
    build: '.'
    image: 'app'
    container_name: 'app_php'
    volumes:
      - .:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    expose:
      - "9000/tcp"
    depends_on:
      - mysql
  nginx:
    image: 'nginx'
    container_name: 'app_nginx'
    ports:
      - "8080:80"
    environment:
      - SYMFONY_ENV=dev
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  mysql:
    image: 'mysql:5.6.26'
    container_name: 'app_mysql'
    ports:
      - 127.0.0.1:3307:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
