new_game:
    path: /
    controller: App\Controller\BlackJackController::newGame

hit:
    path: /
    controller: App\Controller\BlackJackController::hit

show_my_points:
    path: /
    controller: App\Controller\BlackJackController::showMyPoints

show_bank_points:
    path: /
    controller: App\Controller\BlackJackController::showBankPoints
